/*
 * BookApi API (beta ver.)
 *
 *  # Authentication simple no api access, no access token, just a toy project
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// BookApiRouter defines the required methods for binding the api requests to a responses for the BookApi
// The BookApiRouter implementation should parse necessary information from the http request,
// pass the data to a BookApiServicer to perform the required actions, then write the service results to the http response.
type BookApiRouter interface { 
	BookGetBook(http.ResponseWriter, *http.Request)
}


// BookApiServicer defines the api actions for the BookApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type BookApiServicer interface { 
	BookGetBook(context.Context, string, string, string, int32, int32, string, string) (ImplResponse, error)
}
